### ISSUE TITLE
Thou shalt find better commit names!

### ISSUE THREAD

**Issue by grumbach** [tristanponessa/piscine_reloaded#1]
@tristanponessa my brethren, adding a little literature to our daily commits makes our life brighter!

**Comment by tristanponessa** [comment]
anselme im finally here

**Comment by tristanponessa** [comment]
its been a long long road but im finnaly here in this damn 42 and my first grade is -42  i feel very welcomed

**Comment by tristanponessa** [comment]
my commit names are ******

**Comment by grumbach** [comment]
Let's fix this together this weekend!
